import mongoose from 'mongoose';
import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import { requireAdmin } from '@/lib/auth';
import { Project } from '@/models/Project';
import { deleteCloudinaryAsset } from '@/lib/cloudinary';

const validId = (id: string) => mongoose.isValidObjectId(id);
type ImageAsset = { publicId: string; url: string };
export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; if (!validId(id)) return NextResponse.json({ success: false, message: 'Invalid project id' }, { status: 400 }); try { await connectToDatabase(); const project = await Project.findById(id).lean(); if (!project) return NextResponse.json({ success: false, message: 'Project not found' }, { status: 404 }); return NextResponse.json({ success: true, data: project }); } catch { return NextResponse.json({ success: false, message: 'Unable to load project' }, { status: 500 }); } }
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; if (!validId(id)) return NextResponse.json({ success: false, message: 'Invalid project id' }, { status: 400 }); try { await requireAdmin(); await connectToDatabase(); const existing = await Project.findById(id); if (!existing) return NextResponse.json({ success: false, message: 'Project not found' }, { status: 404 }); const body = await request.json(); const existingImages = existing.images as ImageAsset[]; const nextImages = (Array.isArray(body.images) ? body.images : existingImages) as ImageAsset[]; const removedImages = existingImages.filter((image) => !nextImages.some((nextImage) => nextImage.publicId === image.publicId)); await Promise.all(removedImages.map((image) => deleteCloudinaryAsset(image.publicId))); const project = await Project.findByIdAndUpdate(id, body, { new: true, runValidators: true }).lean(); return NextResponse.json({ success: true, message: 'Project updated successfully', data: project }); } catch (error) { return NextResponse.json({ success: false, message: error instanceof Error && error.message === 'UNAUTHORIZED' ? 'Unauthorized' : 'Unable to update project' }, { status: error instanceof Error && error.message === 'UNAUTHORIZED' ? 401 : 500 }); } }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; if (!validId(id)) return NextResponse.json({ success: false, message: 'Invalid project id' }, { status: 400 }); try { await requireAdmin(); await connectToDatabase(); const project = await Project.findByIdAndDelete(id); if (!project) return NextResponse.json({ success: false, message: 'Project not found' }, { status: 404 }); await Promise.all((project.images as ImageAsset[]).map((image) => deleteCloudinaryAsset(image.publicId))); return NextResponse.json({ success: true, message: 'Project deleted successfully' }); } catch (error) { return NextResponse.json({ success: false, message: error instanceof Error && error.message === 'UNAUTHORIZED' ? 'Unauthorized' : 'Unable to delete project' }, { status: error instanceof Error && error.message === 'UNAUTHORIZED' ? 401 : 500 }); } }