import Link from 'next/link';
import { ArrowUpRight, BriefcaseBusiness, Building2, FolderOpen, Image as ImageIcon, Plus } from 'lucide-react';
import { projects } from '@/data/projects';
import { services } from '@/data/services';

const stats = [
  { label: 'Featured projects', value: projects.length, note: 'Published in portfolio', icon: BriefcaseBusiness, accent: 'bg-brand-orange' },
  { label: 'Active services', value: services.length, note: 'Shown on services page', icon: Building2, accent: 'bg-brand-navy' },
  { label: 'Project images', value: projects.length, note: 'Primary gallery assets', icon: ImageIcon, accent: 'bg-[#8c9b75]' },
  { label: 'Total data received', value: projects.length + services.length, note: 'Projects + services records', icon: FolderOpen, accent: 'bg-[#b58c64]' },
];

export default function AdminDashboardPage() {
  return <div className="mx-auto max-w-[1500px] space-y-8">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-sm text-slate-500">Good to see you.</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Your work, at a glance.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Keep the public portfolio sharp by managing the work and services your team is proud to deliver.</p></div><div className="flex gap-3"><Link href="/admin/projects/new" className="inline-flex items-center gap-2 bg-brand-orange px-4 py-3 text-sm font-bold text-white shadow-lg shadow-brand-orange/15 transition hover:bg-orange-700"><Plus size={17} /> Add project</Link><Link href="/admin/services/new" className="inline-flex items-center gap-2 border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-brand-navy transition hover:border-brand-orange"><Plus size={17} /> Add service</Link></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <div key={stat.label} className="border border-slate-200 bg-white p-5 shadow-[0_12px_35px_rgba(20,34,31,0.04)]"><div className="mb-7 flex items-start justify-between"><div className={`flex h-11 w-11 items-center justify-center text-white ${stat.accent}`}><stat.icon size={21} /></div><span className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-600">Live</span></div><p className="text-3xl font-bold tracking-tight text-brand-navy">{stat.value}</p><p className="mt-1 text-sm font-semibold text-brand-navy">{stat.label}</p><p className="mt-2 text-xs text-slate-400">{stat.note}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
      <section className="border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-7"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-orange">Portfolio pulse</p><h3 className="mt-1 text-xl font-bold">Recently featured projects</h3></div><Link href="/admin/projects" className="inline-flex items-center gap-1 text-sm font-bold text-brand-orange hover:text-orange-700">View all <ArrowUpRight size={16} /></Link></div><div className="divide-y divide-slate-100">{projects.slice(0, 4).map((project) => <div key={project.id} className="flex items-center gap-4 px-5 py-4 sm:px-7"><img src={project.image} alt="" className="h-14 w-20 object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-brand-navy">{project.title}</p><p className="mt-1 text-xs text-slate-400">{project.location}</p></div><span className="hidden bg-brand-gray px-3 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500 sm:inline-block">{project.category}</span><ArrowUpRight size={16} className="text-slate-300" /></div>)}</div></section>
      <section className="bg-brand-navy p-6 text-white sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-orange">Quick start</p><h3 className="mt-4 max-w-xs text-2xl font-bold leading-tight">Make the next update count.</h3><p className="mt-4 text-sm leading-6 text-white/60">Your public pages are built around strong imagery and clear project stories. Start with the content that needs attention most.</p><div className="mt-8 space-y-3"><Link href="/admin/projects/new" className="flex items-center justify-between border border-white/15 px-4 py-3 text-sm font-semibold transition hover:border-brand-orange hover:bg-white/5">Create a project <ArrowUpRight size={17} /></Link><Link href="/admin/services/new" className="flex items-center justify-between border border-white/15 px-4 py-3 text-sm font-semibold transition hover:border-brand-orange hover:bg-white/5">Add a service <ArrowUpRight size={17} /></Link></div></section>
    </div>
  </div>;
}