'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import ImageUploader, { UploadedImage } from './ImageUploader';

type Service = { title: string; category: string; shortDescription: string; description: string; features: string[]; image?: UploadedImage };
export default function EditServiceForm({ id }: { id: string }) {
  const router = useRouter(); const [service, setService] = useState<Service | null>(null); const [image, setImage] = useState<UploadedImage[]>([]); const [features, setFeatures] = useState<string[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/services/${id}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.message); setService(result.data); setImage(result.data.image ? [result.data.image] : []); setFeatures(result.data.features?.length ? result.data.features : ['']); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : 'Unable to load service')); }, [id]);
  if (error) return <p role="alert" className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>;
  if (!service) return <p className="text-sm text-slate-500">Loading service...</p>;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const response = await fetch(`/api/services/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: form.get('title'), category: form.get('category'), shortDescription: form.get('shortDescription'), description: form.get('description'), features: features.filter(Boolean), image: image[0] }) }); if (!response.ok) { const result = await response.json(); setError(result.message ?? 'Unable to update service'); } else router.push('/admin/services'); setSaving(false); }
  return <div className="mx-auto max-w-4xl"><Link href="/admin/services" className="text-sm font-bold text-brand-orange">← Back to services</Link><form onSubmit={submit} className="mt-6 border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-orange">Service details</p><h2 className="mt-2 text-3xl font-bold">Edit service</h2><div className="mt-8 grid gap-5"><label><span className="mb-2 block text-sm font-semibold">Service title</span><input name="title" required defaultValue={service.title} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Category</span><input name="category" defaultValue={service.category} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Short description</span><input name="shortDescription" required defaultValue={service.shortDescription} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Full description</span><textarea name="description" required defaultValue={service.description} rows={5} className="field resize-y" /></label><div><span className="mb-2 block text-sm font-semibold">Service image</span><ImageUploader folder="services" value={image} onChange={setImage} /></div><div><span className="mb-2 block text-sm font-semibold">Service features</span>{features.map((feature, index) => <input key={index} value={feature} onChange={(event) => setFeatures(features.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} className="field mb-2" />)}</div></div>{error && <p role="alert" className="mt-5 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end gap-3 border-t border-slate-100 pt-6"><Link href="/admin/services" className="border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</Link><button disabled={saving} className="bg-brand-navy px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save changes'}</button></div></form></div>;
}