'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import ImageUploader, { UploadedImage } from './ImageUploader';

type Project = { title: string; location: string; category: string; description: string; area: string; duration: string; completion: string; client: string; scope: string[]; images: UploadedImage[] };
export default function EditProjectForm({ id }: { id: string }) {
  const router = useRouter(); const [project, setProject] = useState<Project | null>(null); const [images, setImages] = useState<UploadedImage[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/projects/${id}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.message); setProject(result.data); setImages(result.data.images ?? []); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : 'Unable to load project')); }, [id]);
  if (error) return <p role="alert" className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>;
  if (!project) return <p className="text-sm text-slate-500">Loading project...</p>;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const response = await fetch(`/api/projects/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: form.get('title'), location: form.get('location'), category: form.get('category'), description: form.get('description'), area: form.get('area'), duration: form.get('duration'), completion: form.get('completion'), client: form.get('client'), scope: String(form.get('scope') ?? '').split(',').map((item) => item.trim()).filter(Boolean), images }) }); if (!response.ok) { const result = await response.json(); setError(result.message ?? 'Unable to update project'); } else router.push('/admin/projects'); setSaving(false); }
  return <div className="mx-auto max-w-4xl"><Link href="/admin/projects" className="text-sm font-bold text-brand-orange">← Back to projects</Link><form onSubmit={submit} className="mt-6 border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-orange">Project details</p><h2 className="mt-2 text-3xl font-bold">Edit project</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Project title</span><input name="title" required defaultValue={project.title} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Location</span><input name="location" required defaultValue={project.location} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Category</span><select name="category" defaultValue={project.category} className="field"><option>Residential</option><option>Villas</option><option>Commercial</option><option>Renovation</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Project overview</span><textarea name="description" required defaultValue={project.description} rows={5} className="field resize-y" /></label><label><span className="mb-2 block text-sm font-semibold">Area / size</span><input name="area" defaultValue={project.area} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Duration</span><input name="duration" defaultValue={project.duration} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Completion</span><input name="completion" defaultValue={project.completion} className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Client</span><input name="client" defaultValue={project.client} className="field" /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Scope of work</span><input name="scope" defaultValue={project.scope.join(', ')} className="field" /></label><div className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Project images</span><ImageUploader folder="projects" multiple value={images} onChange={setImages} /></div></div>{error && <p role="alert" className="mt-5 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end gap-3 border-t border-slate-100 pt-6"><Link href="/admin/projects" className="border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</Link><button disabled={saving} className="bg-brand-navy px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save changes'}</button></div></form></div>;
}