'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import ImageUploader, { UploadedImage } from './ImageUploader';

export default function ProjectForm() {
  const router = useRouter(); const [images, setImages] = useState<UploadedImage[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); const body = { title: form.get('title'), location: form.get('location'), category: form.get('category'), description: form.get('description'), area: form.get('area'), duration: form.get('duration'), completion: form.get('completion'), client: form.get('client'), images, scope: String(form.get('scope') ?? '').split(',').map((item) => item.trim()).filter(Boolean) }; try { const response = await fetch('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? 'Unable to create project'); router.push('/admin/projects'); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Unable to create project'); } finally { setSaving(false); } }
  return <div className="mx-auto max-w-4xl"><Link href="/admin/projects" className="text-sm font-bold text-brand-orange">← Back to projects</Link><form onSubmit={submit} className="mt-6 border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-orange">Project details</p><h2 className="mt-2 text-3xl font-bold">Add a featured project</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Project title</span><input name="title" required placeholder="Luxury Family Villa" className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Location</span><input name="location" required placeholder="Bengaluru, Karnataka" className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Category</span><select name="category" className="field"><option>Residential</option><option>Villas</option><option>Commercial</option><option>Renovation</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Project overview</span><textarea name="description" required rows={5} placeholder="Describe the project, scope, and outcome..." className="field resize-y" /></label><label><span className="mb-2 block text-sm font-semibold">Area / size</span><input name="area" placeholder="8,200 sq.ft." className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Duration</span><input name="duration" placeholder="18 Months" className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Completion</span><input name="completion" placeholder="January 2026" className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Client</span><input name="client" placeholder="Optional" className="field" /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Scope of work</span><input name="scope" placeholder="Construction, Interiors, Landscaping" className="field" /></label><div className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Project images</span><ImageUploader folder="projects" multiple value={images} onChange={setImages} /></div></div>{error && <p role="alert" className="mt-5 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end gap-3 border-t border-slate-100 pt-6"><Link href="/admin/projects" className="border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</Link><button disabled={saving} className="bg-brand-navy px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save project'}</button></div></form></div>;
}