'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import ImageUploader, { UploadedImage } from './ImageUploader';

export default function ServiceForm() {
  const router = useRouter(); const [image, setImage] = useState<UploadedImage[]>([]); const [features, setFeatures] = useState<string[]>(['']); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); const body = { title: form.get('title'), shortDescription: form.get('shortDescription'), description: form.get('description'), category: form.get('category'), features: features.map((item) => item.trim()).filter(Boolean), image: image[0] }; try { const response = await fetch('/api/services', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? 'Unable to create service'); router.push('/admin/services'); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Unable to create service'); } finally { setSaving(false); } }
  return <div className="mx-auto max-w-4xl"><Link href="/admin/services" className="text-sm font-bold text-brand-orange">← Back to services</Link><form onSubmit={submit} className="mt-6 border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-orange">Service details</p><h2 className="mt-2 text-3xl font-bold">Add a service</h2><div className="mt-8 grid gap-5"><label><span className="mb-2 block text-sm font-semibold">Service title</span><input name="title" required placeholder="Residential Construction" className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Category</span><input name="category" placeholder="Construction" className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Short description</span><input name="shortDescription" required placeholder="Complete home construction from planning to handover." className="field" /></label><label><span className="mb-2 block text-sm font-semibold">Full description</span><textarea name="description" required rows={5} placeholder="Add the detail your clients need..." className="field resize-y" /></label><div><span className="mb-2 block text-sm font-semibold">Service image</span><ImageUploader folder="services" value={image} onChange={setImage} /></div><div><span className="mb-2 block text-sm font-semibold">Service features</span>{features.map((feature, index) => <div key={index} className="mb-2 flex gap-2"><input value={feature} onChange={(event) => setFeatures(features.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder={`Feature ${index + 1}`} className="field" />{features.length > 1 && <button type="button" onClick={() => setFeatures(features.filter((_, itemIndex) => itemIndex !== index))} className="border border-slate-200 px-3 text-slate-400">×</button>}</div>)}<button type="button" onClick={() => setFeatures([...features, ''])} className="text-sm font-bold text-brand-orange">+ Add feature</button></div></div>{error && <p role="alert" className="mt-5 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end gap-3 border-t border-slate-100 pt-6"><Link href="/admin/services" className="border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</Link><button disabled={saving} className="bg-brand-navy px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save service'}</button></div></form></div>;
}