import mongoose from 'mongoose';
import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import { requireAdmin } from '@/lib/auth';
import { Service } from '@/models/Service';
import { deleteCloudinaryAsset } from '@/lib/cloudinary';

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; if (!mongoose.isValidObjectId(id)) return NextResponse.json({ success: false, message: 'Invalid service id' }, { status: 400 }); try { await connectToDatabase(); const service = await Service.findById(id).lean(); if (!service) return NextResponse.json({ success: false, message: 'Service not found' }, { status: 404 }); return NextResponse.json({ success: true, data: service }); } catch { return NextResponse.json({ success: false, message: 'Unable to load service' }, { status: 500 }); } }
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; if (!mongoose.isValidObjectId(id)) return NextResponse.json({ success: false, message: 'Invalid service id' }, { status: 400 }); try { await requireAdmin(); await connectToDatabase(); const existing = await Service.findById(id); if (!existing) return NextResponse.json({ success: false, message: 'Service not found' }, { status: 404 }); const body = await request.json(); if (body.image?.publicId && body.image.publicId !== existing.image?.publicId) await deleteCloudinaryAsset(existing.image?.publicId ?? ''); const service = await Service.findByIdAndUpdate(id, body, { new: true, runValidators: true }).lean(); return NextResponse.json({ success: true, message: 'Service updated successfully', data: service }); } catch (error) { return NextResponse.json({ success: false, message: error instanceof Error && error.message === 'UNAUTHORIZED' ? 'Unauthorized' : 'Unable to update service' }, { status: error instanceof Error && error.message === 'UNAUTHORIZED' ? 401 : 500 }); } }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; if (!mongoose.isValidObjectId(id)) return NextResponse.json({ success: false, message: 'Invalid service id' }, { status: 400 }); try { await requireAdmin(); await connectToDatabase(); const service = await Service.findByIdAndDelete(id); if (!service) return NextResponse.json({ success: false, message: 'Service not found' }, { status: 404 }); await deleteCloudinaryAsset(service.image?.publicId ?? ''); return NextResponse.json({ success: true, message: 'Service deleted successfully' }); } catch (error) { return NextResponse.json({ success: false, message: error instanceof Error && error.message === 'UNAUTHORIZED' ? 'Unauthorized' : 'Unable to delete service' }, { status: error instanceof Error && error.message === 'UNAUTHORIZED' ? 401 : 500 }); } }