'use client';

import Link from 'next/link';
import { Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { services as fallbackServices } from '@/data/services';

type Service = { id: string; title: string; description: string; image: string };

export default function AdminServicesPage() {
  const [items, setItems] = useState<Service[]>(fallbackServices); const [query, setQuery] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/services?limit=50').then(async (response) => { const result = await response.json(); if (response.ok && result.data.length) setItems(result.data.map((item: { _id: string; title: string; shortDescription: string; description: string; image?: { url: string } }) => ({ id: item._id, title: item.title, description: item.shortDescription || item.description, image: item.image?.url ?? fallbackServices[0].image }))); }).catch(() => undefined); }, []);
  const filtered = useMemo(() => items.filter((service) => service.title.toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function remove(id: string, title: string) { if (!window.confirm(`Are you sure you want to delete ${title}?`)) return; const response = await fetch(`/api/services/${id}`, { method: 'DELETE' }); if (response.ok) { setItems(items.filter((item) => item.id !== id)); setMessage('Service deleted successfully.'); } else setMessage('Unable to delete this service.'); }
  return <div className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm text-slate-500">What you do</p><h2 className="text-3xl font-bold tracking-tight">Services</h2><p className="mt-2 text-sm text-slate-500">Keep your service offering clear, current, and easy to explore.</p></div><Link href="/admin/services/new" className="inline-flex items-center justify-center gap-2 bg-brand-orange px-4 py-3 text-sm font-bold text-white shadow-lg shadow-brand-orange/15 hover:bg-orange-700"><Plus size={17} /> New service</Link></div>{message && <p role="status" className="border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}<section className="overflow-hidden border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="relative w-full sm:max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search services" className="w-full border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-brand-orange" /></div><span className="text-sm text-slate-400">{filtered.length} services</span></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="bg-brand-gray text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500"><tr><th className="px-5 py-4">Service</th><th className="px-5 py-4">Description</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((service) => <tr key={service.id} className="hover:bg-[#fcfbf9]"><td className="px-5 py-4"><div className="flex items-center gap-3"><img src={service.image} alt="" className="h-12 w-16 object-cover" /><p className="font-bold text-brand-navy">{service.title}</p></div></td><td className="max-w-md px-5 py-4 text-sm leading-6 text-slate-500">{service.description}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Link href="/services" className="rounded-lg p-2 text-slate-400 hover:bg-brand-gray hover:text-brand-navy" aria-label={`View ${service.title}`}><Eye size={17} /></Link><Link href={`/admin/services/edit/${service.id}`} className="rounded-lg p-2 text-slate-400 hover:bg-brand-gray hover:text-brand-navy" aria-label={`Edit ${service.title}`}><Pencil size={17} /></Link><button type="button" onClick={() => remove(service.id, service.title)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" aria-label={`Delete ${service.title}`}><Trash2 size={17} /></button></div></td></tr>)}</tbody></table></div><div className="border-t border-slate-100 px-5 py-4 text-xs text-slate-400">Showing {filtered.length} of {items.length} services</div></section></div>;
}
